cc_library(
    name = "date",
    srcs = ["date.cpp"],
    hdrs = ["date.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "fileMgmt",
    srcs = ["fileMgmt.cpp"],
    hdrs = ["fileMgmt.h"],
    deps = [":date"],
    visibility = ["//visibility:public"],
)